// catalogo-jogos.js

export const CATALOGO_JOGOS = [
	
	// Pré-Escolar
    { nome: "Já Sei Contar", icone: "pre/icones/ja_sei_contar.png", link: "pre/sei-contar/", ano: "Pré-Escolar" },
    { nome: "Super Cores", icone: "pre/icones/super_cores.png", link: "pre/super-cores/", ano: "Pré-Escolar" },
    { nome: "Diferenças", icone: "pre/icones/diferencas.png", link: "pre/diferencas/", ano: "Pré-Escolar" },
    { nome: "Memória Mágica", icone: "pre/icones/memoria_magica.png", link: "pre/memoria/", ano: "Pré-Escolar" },
    { nome: "Sombras", icone: "pre/icones/sombras.png", link: "pre/sombras/", ano: "Pré-Escolar" },
    { nome: "Detetive", icone: "pre/icones/detetive.png", link: "pre/procurar/", ano: "Pré-Escolar" },
    { nome: "Super Detetive", icone: "pre/icones/super-detetive.png", link: "pre/procurar-2/", ano: "Pré-Escolar" },
    { nome: "Sequências", icone: "pre/icones/sequencias.png", link: "pre/sequencias/", ano: "Pré-Escolar" },
    { nome: "Frente e Trás", icone: "pre/icones/frente_tras.png", link: "pre/frente-tras/", ano: "Pré-Escolar" },
    { nome: "Rimas", icone: "pre/icones/rimas.png", link: "pre/rimas/", ano: "Pré-Escolar" },
    { nome: "Reciclagem", icone: "pre/icones/reciclagem.png", link: "pre/reciclagem/", ano: "Pré-Escolar" },
    { nome: "Super Memória", icone: "pre/icones/super_memoria.png", link: "pre/super-memoria/", ano: "Pré-Escolar" },
	{ nome: "Contar Sílabas", icone: "pre/icones/contar_silabas.png", link: "pre/contar-silabas/", ano: "Pré-Escolar" },
	{ nome: "Vogais", icone: "pre/icones/vogais.png", link: "pre/vogais/", ano: "Pré-Escolar" }, 
	{ nome: "Vamos Contar!", icone: "pre/icones/vamos_contar.png", link: "pre/vamos-contar/", ano: "Pré-Escolar" },
	{ nome: "Vogais Faladas", icone: "pre/icones/vogais_faladas.png", link: "pre/vogais-faladas/", ano: "Pré-Escolar" },
	{ nome: "Labirintos", icone: "pre/icones/labirintos.png", link: "pre/labirintos/", ano: "Pré-Escolar" },
	{ nome: "Sem Par", icone: "pre/icones/sem_par.png", link: "pre/sem-par/", ano: "Pré-Escolar" },
	{ nome: "Puzzles Mágicos", icone: "pre/icones/puzzles_magicos.png", link: "pre/puzzles-magicos/", ano: "Pré-Escolar" },
	{ nome: "Números Coloridos", icone: "pre/icones/numeros_cores.png", link: "pre/numeros-cores/", ano: "Pré-Escolar" },
	{ nome: "Dados Mágicos", icone: "pre/icones/dados_magicos.png", link: "pre/dados-magicos/", ano: "Pré-Escolar" },
	{ nome: "Sons dos Bichos", icone: "pre/icones/sons_bichos.png", link: "pre/sons_bichos/", ano: "Pré-Escolar" },
	{ nome: "Quem Sou Eu?", icone: "pre/icones/quem_sou_eu.png", link: "pre/quem-sou-eu/", ano: "Pré-Escolar" },
	{ nome: "O Robô Construtor", icone: "pre/icones/robo_construtor.png", link: "pre/robo-construtor/", ano: "Pré-Escolar" },
	{ nome: "Pixel Art", icone: "pre/icones/pixel_art.png", link: "pre/pixel-art/", ano: "Pré-Escolar" },
	{ nome: "Vamos Colorir", icone: "pre/icones/vamos_colorir.png", link: "pre/vamos-colorir/", ano: "Pré-Escolar" },
	{ nome: "Memória Falada", icone: "pre/icones/memoria_falada.png", link: "pre/memoria-falada/", ano: "Pré-Escolar" },
	{ nome: "Metades", icone: "pre/icones/metades.png", link: "pre/metades/", ano: "Pré-Escolar" },
	{ nome: "Som Inicial", icone: "pre/icones/som_inicial.png", link: "pre/som-inicial/", ano: "Pré-Escolar" },
	{ nome: "Ouvir e Descobrir", icone: "pre/icones/ouvir_descobrir.png", link: "pre/ouvir-descobrir/", ano: "Pré-Escolar" },
	{ nome: "Ouvir e Resolver", icone: "pre/icones/ouvir_resolver.png", link: "pre/ouvir-resolver/", ano: "Pré-Escolar" },
	{ nome: "A Magia dos Números", icone: "pre/icones/magia_numeros.png", link: "pre/magia-numeros/", ano: "Pré-Escolar" },
	{ nome: "Magia Musical", icone: "pre/icones/magia_musical.png", link: "pre/magia-musical/", ano: "Pré-Escolar" },
	{ nome: "Os Cestos do Leo", icone: "pre/icones/comida_saudavel.png", link: "pre/comida-saudavel/", ano: "Pré-Escolar" },
	{ nome: "O Monstro das Formas", icone: "pre/icones/monstro_formas.png", link: "pre/monstro-formas/", ano: "Pré-Escolar" },
	{ nome: "A Cidade dos Sentidos", icone: "pre/icones/cidade_sentidos.png", link: "pre/cidade-sentidos/", ano: "Pré-Escolar" },
	{ nome: "O Monstro das Emoções", icone: "pre/icones/monstro_emocoes.png", link: "pre/monstro-emocoes/", ano: "Pré-Escolar" },
	{ nome: "A Roleta Maluca", icone: "pre/icones/roleta_maluca.png", link: "pre/roleta-maluca/", ano: "Pré-Escolar" },
	{ nome: "O Animal Favorito", icone: "pre/icones/animal_favorito.png", link: "pre/animal_favorito/", ano: "Pré-Escolar" },
	{ nome: "A Casa dos Animais", icone: "pre/icones/casa_animais.png", link: "pre/casa-animais/", ano: "Pré-Escolar" },
	{ nome: "Os Nossos Heróis", icone: "pre/icones/nossos_herois.png", link: "pre/nossos-herois/", ano: "Pré-Escolar" },
	{ nome: "Detetives do Planeta", icone: "pre/icones/detetives_planeta.png", link: "pre/detetives-planeta/", ano: "Pré-Escolar" },
	{ nome: "O Ratinho Comilão", icone: "pre/icones/ratinho_comilao.png", link: "pre/ratinho-comilao/", ano: "Pré-Escolar" },
	{ nome: "O Polvo Pintor", icone: "pre/icones/polvo_pintor.png", link: "pre/polvo-pintor/", ano: "Pré-Escolar" },
	{ nome: "Esquerda ou Direita?", icone: "pre/icones/esquerda_direita.png", link: "pre/esquerda-direita/", ano: "Pré-Escolar" },
	{ nome: "Tamanhos dos Nomes", icone: "pre/icones/tamanho_nomes.png", link: "pre/tamanho-nomes/", ano: "Pré-Escolar" },
	{ nome: "Oceano dos Números", icone: "pre/icones/oceano_numeros.png", link: "pre/oceano-numeros/", ano: "Pré-Escolar" },
	{ nome: "O Radar", icone: "pre/icones/radar.png", link: "pre/radar/", ano: "Pré-Escolar" },  
  
	// ------------------------------------
	// 1º ANO
	// ------------------------------------

	// Português (pt)
	{ nome: "O Meu Teclado", icone: "1/icones/meu_teclado.png", link: "1/pt/meu-teclado/", ano: "1º Ano" },
	{ nome: "Palavra Certa", icone: "1/icones/palavra_certa.png", link: "1/pt/palavra-certa/", ano: "1º Ano" },
	{ nome: "Letras em Falta", icone: "1/icones/letra_em_falta.png", link: "1/pt/letras-em-falta/", ano: "1º Ano" },
	{ nome: "Contar Sílabas", icone: "1/icones/contar_silabas.png", link: "1/pt/contar-silabas/", ano: "1º Ano" },
	{ nome: "Rimas", icone: "1/icones/rimas.png", link: "1/pt/rimas/", ano: "1º Ano" },
	{ nome: "Comboio das Letras", icone: "1/icones/comboio_letras.png", link: "1/pt/comboio-letras/", ano: "1º Ano" },
	{ nome: "Código Secreto", icone: "1/icones/codigo_secreto.png", link: "1/pt/codigo-secreto/", ano: "1º Ano" },
	{ nome: "Sílaba Inicial", icone: "1/icones/primeira_silaba.png", link: "1/pt/primeira-silaba/", ano: "1º Ano" },
	{ nome: "28 Palavras", icone: "1/icones/28_palavras.png", link: "1/pt/28-palavras/", ano: "1º Ano" }, 
	{ nome: "Comboio das Sílabas", icone: "1/icones/comboio_silabas.png", link: "1/pt/comboio-silabas/", ano: "1º Ano" }, 
	{ nome: "Memória de Imagens", icone: "1/icones/memoria_imagens.png", link: "1/pt/memoria-imagens", ano: "1º Ano" },
	{ nome: "Palavras e Imagens", icone: "1/icones/memoria.png", link: "1/pt/memoria", ano: "1º Ano" },
	{ nome: "Ordenar Sílabas", icone: "1/icones/ordenar_silabas.png", link: "1/pt/ordenar-silabas", ano: "1º Ano" },
	{ nome: "Escrever Sílabas", icone: "1/icones/puzzle_silabas.png", link: "1/pt/escrever-silabas", ano: "1º Ano" },
	{ nome: "Bolhas de Sabão", icone: "1/icones/bolhas_sabao.png", link: "1/pt/bolhas", ano: "1º Ano" },
	{ nome: "Monstro das Sílabas", icone: "1/icones/monstro_silabas.png", link: "1/pt/monstro-silabas", ano: "1º Ano" },
	{ nome: "Escrever Palavras", icone: "1/icones/ditado_palavras.png", link: "1/pt/escrever-palavras", ano: "1º Ano" },
	{ nome: "Ditado de Palavras", icone: "1/icones/ditado_palavras.png", link: "1/pt/ditado-palavras", ano: "1º Ano" },
	{ nome: "Sopa de letras", icone: "1/icones/sopa_letras.png", link: "1/pt/sopa-letras", ano: "1º Ano" },
	{ nome: "Copiar Frases", icone: "1/icones/copiar_frases.png", link: "1/pt/copia-frases", ano: "1º Ano" }, 
	{ nome: "Lanterna Mágica", icone: "1/icones/lanterna_magica.png", link: "1/pt/lanterna-magica", ano: "1º Ano" },
	{ nome: "Verdadeiro ou Falso", icone: "1/icones/verdadeiro_falso.png", link: "1/pt/verdadeiro-falso", ano: "1º Ano" },
	{ nome: "Palavra Flash", icone: "1/icones/palavra_flash.png", link: "1/pt/palavra-flash", ano: "1º Ano" },
	{ nome: "Caixa das Adivinhas", icone: "1/icones/caixa_adivinhas.png", link: "1/pt/caixa-adivinhas", ano: "1º Ano" },
	{ nome: "Jogo da Forca", icone: "1/icones/jogo_forca.png", link: "1/pt/forca", ano: "1º Ano" },
	{ nome: "Puzzle das Sílabas", icone: "1/icones/puzzle_silabas.png", link: "1/pt/puzzle-silabas", ano: "1º Ano" },
	{ nome: "Vogais", icone: "1/icones/vogais.png", link: "1/pt/vogais", ano: "1º Ano" },
	{ nome: "Cruzadas de Animais", icone: "1/icones/cruzadas_animais.png", link: "1/pt/cruzadas-animais", ano: "1º Ano" },
	{ nome: "Roda a Frase", icone: "1/icones/roda_frase.png", link: "1/pt/roda-frase", ano: "1º Ano" },
	{ nome: "Ordem Alfabética", icone: "1/icones/ordem_alfabetica.png", link: "1/pt/ordem-alfabetica", ano: "1º Ano" },
	{ nome: "Ligar Letras", icone: "1/icones/ligar_letras.png", link: "1/pt/ligar-letras", ano: "1º Ano" },
	{ nome: "Monstro das Imagens", icone: "1/icones/monstro_imagens.png", link: "1/pt/monstro-imagens", ano: "1º Ano" },
	{ nome: "O Ritmo das Palavras", icone: "1/icones/ritmo_palavras.png", link: "1/pt/ritmo-palavras", ano: "1º Ano" },

	// Matemática (mat)
	{ nome: "Vamos Contar!", icone: "1/icones/vamos_contar.png", link: "1/mat/contagens/", ano: "1º Ano" },
	{ nome: "O Detetive", icone: "1/icones/detetive.png", link: "1/mat/detetive/", ano: "1º Ano" },
	{ nome: "Camião de Carga", icone: "1/icones/camiao_carga.png", link: "1/mat/camiao-carga/", ano: "1º Ano" }, 
	{ nome: "Sapo Saltitão", icone: "1/icones/sapo_saltitao.png", link: "1/mat/sapo-saltitao/", ano: "1º Ano" }, 
	{ nome: "Gráficos", icone: "1/icones/graficos.png", link: "1/mat/graficos/", ano: "1º Ano" },
	{ nome: "Ligar Quantidades", icone: "1/icones/ligar_quantidades.png", link: "1/mat/ligar-quantidades/", ano: "1º Ano" },
	{ nome: "Desafio Final", icone: "1/icones/quiz.png", link: "1/mat/quiz/", ano: "1º Ano" }, 
	{ nome: "Memória de Números", icone: "1/icones/memoria_numeros.png", link: "1/mat/memoria-numeros", ano: "1º Ano" },
	{ nome: "Máquina de Somar", icone: "1/icones/maquina_somar.png", link: "1/mat/maquina-somar", ano: "1º Ano" },
	{ nome: "Máquina de Subtrair", icone: "1/icones/maquina_subtrair.png", link: "1/mat/maquina-subtrair", ano: "1º Ano" },
	{ nome: "Comboio das Sequências", icone: "1/icones/comboio_sequencias.png", link: "1/mat/sequencias", ano: "1º Ano" },
	{ nome: "Missão Espacial", icone: "1/icones/missao_espacial.png", link: "1/mat/missao-espacial", ano: "1º Ano" },
	{ nome: "Torre de Blocos", icone: "1/icones/torre_blocos.png", link: "1/mat/torre-blocos", ano: "1º Ano" },
	{ nome: "O Monstro da Balança", icone: "1/icones/monstro_balanca.png", link: "1/mat/monstro-balanca", ano: "1º Ano" },
	{ nome: "Viagem dos Números", icone: "1/icones/viagem_numeros.png", link: "1/mat/viagem-numeros", ano: "1º Ano" },
	{ nome: "Cálculo por Decomposição", icone: "1/icones/calculo_decomposicao.png", link: "1/mat/calculo-decomposicao", ano: "1º Ano" },
	{ nome: "Os Amigos do 10", icone: "1/icones/amigos_10.png", link: "1/mat/amigos-10", ano: "1º Ano" },
	{ nome: "Grelha do 100", icone: "1/icones/grelha_100.png", link: "1/mat/grelha-100", ano: "1º Ano" },
	{ nome: "Sólidos e Figuras", icone: "1/icones/solidos_figuras.png", link: "1/mat/solidos-figuras", ano: "1º Ano" },
	{ nome: "O Ábaco Mágico", icone: "1/icones/abaco.png", link: "1/mat/abaco", ano: "1º Ano" },
	{ nome: "Mistérios na Quinta", icone: "1/icones/misterios_quinta.png", link: "1/mat/misterios-quinta", ano: "1º Ano" },

	// Estudo do Meio (em)
	{ nome: "Reciclagem", icone: "1/icones/reciclagem.png", link: "1/em/reciclagem/", ano: "1º Ano" }, 
	{ nome: "Profissões", icone: "1/icones/profissoes.png", link: "1/em/profissoes/", ano: "1º Ano" }, 
	{ nome: "Roupas e Estações", icone: "1/icones/tempo.png", link: "1/em/roupas-estacoes/", ano: "1º Ano" },
	{ nome: "Memória do Corpo", icone: "1/icones/memoria_corpo.png", link: "1/em/corpo/", ano: "1º Ano" },
	{ nome: "Memória Saudável", icone: "1/icones/memoria_saudavel.png", link: "1/em/vida-saudavel/", ano: "1º Ano" },
	{ nome: "Memória do Vestuário", icone: "1/icones/memoria_vestuario.png", link: "1/em/vestuario/", ano: "1º Ano" },
	{ nome: "Memória dos Alimentos", icone: "1/icones/memoria_alimentos.png", link: "1/em/alimentos/", ano: "1º Ano" },
	{ nome: "Memória dos Animais", icone: "1/icones/memoria_animais.png", link: "1/em/animais/", ano: "1º Ano" },
	{ nome: "Memória do Tempo", icone: "1/icones/memoria_tempo.png", link: "1/em/tempo/", ano: "1º Ano" },
	{ nome: "A Família", icone: "1/icones/familia.png", link: "1/em/familia/", ano: "1º Ano" },

	// ------------------------------------
	// 2º ANO
	// ------------------------------------

	// Português (pt)
	{ nome: "Masculino e Feminino", icone: "2/icones/genero.png", link: "2/pt/genero/", ano: "2º Ano" },
	{ nome: "Singular e Plural", icone: "2/icones/numero.png", link: "2/pt/numero", ano: "2º Ano" },
	{ nome: "Sinónimos", icone: "2/icones/sinonimos.png", link: "2/pt/sinonimos", ano: "2º Ano" },
	{ nome: "Antónimos", icone: "2/icones/antonimos.png", link: "2/pt/antonimos", ano: "2º Ano" },
	{ nome: "Sinónimos e Antónimos", icone: "2/icones/sinonimos_antonimos.png", link: "2/pt/sinonimos-antonimos", ano: "2º Ano" },
	{ nome: "Pontos e Acentos", icone: "2/icones/pontos_acentos.png", link: "2/pt/pontos-acentos", ano: "2º Ano" },
	{ nome: "Chuva de Palavras", icone: "2/icones/chuva_palavras.png", link: "2/pt/classes", ano: "2º Ano" },
	{ nome: "Construtor de Frases", icone: "2/icones/construtor_frases.png", link: "2/pt/ordenar-frases", ano: "2º Ano" },
	{ nome: "Ler e Copiar", icone: "2/icones/copiar_textos.png", link: "2/pt/escrita-textos", ano: "2º Ano" },
	{ nome: "Letras Mágicas", icone: "2/icones/letras_magicas.png", link: "2/pt/letras-magicas", ano: "2º Ano" },
	{ nome: "Aventura dos Sons", icone: "2/icones/aventura_sons.png", link: "2/pt/aventura-sons", ano: "2º Ano" },
	{ nome: "Missão dos Sons", icone: "2/icones/missao_sons.png", link: "2/pt/missao-sons", ano: "2º Ano" },
	{ nome: "Ditado de Frases", icone: "2/icones/ditado_frases.png", link: "2/pt/ditado-frases", ano: "2º Ano" },
	{ nome: "Palavras Cruzadas", icone: "2/icones/palavras_cruzadas.png", link: "2/pt/cruzadas", ano: "2º Ano" },
	{ nome: "Cruzadas de Animais", icone: "2/icones/cruzadas_animais.png", link: "2/pt/cruzadas-animais/", ano: "2º Ano" },
	{ nome: "Sopa de Letras", icone: "2/icones/sopa_letras.png", link: "2/pt/sopa-letras/", ano: "2º Ano" },
	{ nome: "Divisão Silábica", icone: "2/icones/divisao_silabica.png", link: "2/pt/divisao-silabica/", ano: "2º Ano" },
	{ nome: "Palavras por Minuto", icone: "2/icones/palavras_minuto.png", link: "2/pt/palavras-minuto/", ano: "2º Ano" },
	{ nome: "Super Quiz", icone: "2/icones/quiz_portugues.png", link: "2/pt/quiz/", ano: "2º Ano" },
	{ nome: "Determinantes Artigos", icone: "2/icones/determinantes_artigos.png", link: "2/pt/determinantes-artigos/", ano: "2º Ano" },

	// Matemática (mat)
	{ nome: "Máquina das Tabuadas", icone: "2/icones/tabuadas.png", link: "2/mat/tabuadas/", ano: "2º Ano" },
	{ nome: "Missão Matemática", icone: "2/icones/missao_matematica.png", link: "2/mat/missao-matematica/", ano: "2º Ano" },
	{ nome: "Balança da Adição", icone: "2/icones/balanca_adicao.png", link: "2/mat/balanca-adicao/", ano: "2º Ano" },
	{ nome: "Balança da Subtração", icone: "2/icones/balanca_subtracao.png", link: "2/mat/balanca-subtracao/", ano: "2º Ano" },
	{ nome: "O Monstro Guloso", icone: "2/icones/comparar.png", link: "2/mat/comparar/", ano: "2º Ano" },
	{ nome: "Construtor de Números", icone: "2/icones/construtor_numeros.png", link: "2/mat/construtor-numeros/", ano: "2º Ano" },
	{ nome: "O Trator MAB", icone: "2/icones/trator_mab.png", link: "2/mat/trator-mab/", ano: "2º Ano" },
	{ nome: "Problemas Mágicos", icone: "2/icones/problemas_magicos.png", link: "2/mat/problemas-magicos/", ano: "2º Ano" },
	{ nome: "Frações Divertidas", icone: "2/icones/fracoes.png", link: "2/mat/fracoes/", ano: "2º Ano" },
	{ nome: "Cruzadas Numéricas", icone: "2/icones/cruzadas_numericas.png", link: "2/mat/cruzadas-numericas/", ano: "2º Ano" },
	{ nome: "Estratégias de Cálculo", icone: "2/icones/estrategias_calculo.png", link: "2/mat/estrategias-calculo/", ano: "2º Ano" },
	{ nome: "Tabuadas Flash", icone: "2/icones/tabuadas_flash.png", link: "2/mat/tabuadas-flash/", ano: "2º Ano" },
	{ nome: "Sequências de Repetição", icone: "2/icones/sequencias_repeticao.png", link: "2/mat/sequencias-repeticao/", ano: "2º Ano" },
	{ nome: "Sequências de Crescimento", icone: "2/icones/sequencias_crescimento.png", link: "2/mat/sequencias-crescimento/", ano: "2º Ano" },
	{ nome: "Comboio das Sequências", icone: "2/icones/comboio_sequencias.png", link: "2/mat/comboio-sequencias/", ano: "2º Ano" },
	{ nome: "Revisão de Sequências", icone: "2/icones/sequencias_revisoes.png", link: "2/mat/sequencias-revisoes/", ano: "2º Ano" },
	{ nome: "Simetria", icone: "2/icones/simetria.png", link: "2/mat/simetria/", ano: "2º Ano" },
	{ nome: "Gráficos", icone: "2/icones/graficos.png", link: "2/mat/graficos/", ano: "2º Ano" },
	{ nome: "Figuras e Sólidos", icone: "2/icones/figuras_solidos.png", link: "2/mat/figuras-solidos/", ano: "2º Ano" },
	{ nome: "Super Quiz", icone: "2/icones/quiz_matematica.png", link: "2/mat/quiz/", ano: "2º Ano" },
	{ nome: "Enigmas da Selva", icone: "2/icones/enigmas_selva.png", link: "2/mat/enigmas-selva/", ano: "2º Ano" },
	{ nome: "Problemas no Caderno", icone: "2/icones/problemas_caderno.png", link: "2/mat/problemas-caderno/", ano: "2º Ano" },

	// Estudo do Meio (em)
	{ nome: "Animais", icone: "2/icones/animais.png", link: "2/em/animais/", ano: "2º Ano" },
	{ nome: "O Corpo Humano", icone: "2/icones/corpo_humano.png", link: "2/em/corpo-humano/", ano: "2º Ano" },
	{ nome: "Estados da Água", icone: "2/icones/estados_agua.png", link: "2/em/estados-agua/", ano: "2º Ano" },
	{ nome: "As Plantas", icone: "2/icones/plantas.png", link: "2/em/plantas/", ano: "2º Ano" },
	{ nome: "Sopa de Letras", icone: "2/icones/sopa_letras_meios_comunicacao.png", link: "2/em/sopa-letras/", ano: "2º Ano" },
	{ nome: "Máquina do Tempo", icone: "2/icones/maquina_tempo.png", link: "2/em/maquina-tempo/", ano: "2º Ano" },
	{ nome: "Flutua ou Afunda?", icone: "2/icones/flutua_afunda.png", link: "2/em/flutua-afunda/", ano: "2º Ano" },
	{ nome: "Os 5 Sentidos", icone: "2/icones/5_sentidos.png", link: "2/em/5-sentidos/", ano: "2º Ano" },
	{ nome: "A Família", icone: "2/icones/familia.png", link: "2/em/familia/", ano: "2º Ano" },
	{ nome: "Super Quiz", icone: "2/icones/quiz_estudo_meio.png", link: "2/em/quiz/", ano: "2º Ano" },  

	// ------------------------------------
	// 3º ANO
	// ------------------------------------

	// Português (pt)
	{ nome: "Determinantes Artigos", icone: "3/icones/determinantes_artigos.png", link: "3/pt/determinantes-artigos/", ano: "3º Ano" },
	{ nome: "Sinónimos e Antónimos", icone: "3/icones/sinonimos_antonimos.png", link: "3/pt/sinonimos-antonimos/", ano: "3º Ano" },
	{ nome: "Graus das Palavras", icone: "3/icones/graus.png", link: "3/pt/graus/", ano: "3º Ano" },
	{ nome: "Revisões", icone: "3/icones/revisoes.png", link: "3/pt/revisoes/", ano: "3º Ano" },
	{ nome: "Pronomes Pessoais", icone: "3/icones/pronomes_pessoais.png", link: "3/pt/pronomes-pessoais/", ano: "3º Ano" },
	{ nome: "Acentuação", icone: "3/icones/acentuacao.png", link: "3/pt/acentuacao/", ano: "3º Ano" },
	{ nome: "O Mistério dos Sinais", icone: "3/icones/sinais.png", link: "3/pt/sinais/", ano: "3º Ano" },
	{ nome: "Quantificadores Numerais", icone: "3/icones/quantificadores_numerais.png", link: "3/pt/quantificadores-numerais/", ano: "3º Ano" },
	{ nome: "A Viagem dos Verbos", icone: "3/icones/viagem_verbos.png", link: "3/pt/viagem-verbos/", ano: "3º Ano" },
	{ nome: "Grupos nas Frases", icone: "3/icones/grupos_frases.png", link: "3/pt/grupos-frases/", ano: "3º Ano" },
	{ nome: "Advérbios", icone: "3/icones/adverbios.png", link: "3/pt/adverbios/", ano: "3º Ano" },
	{ nome: "Conectores Discursivos", icone: "3/icones/conectores_discursivos.png", link: "3/pt/conectores-discursivos/", ano: "3º Ano" },
	{ nome: "Determinantes", icone: "3/icones/determinantes.png", link: "3/pt/determinantes/", ano: "3º Ano" },
	{ nome: "Fábrica das Palavras", icone: "3/icones/fabrica_palavras.png", link: "3/pt/fabrica-palavras/", ano: "3º Ano" },
	{ nome: "Mistérios do Português", icone: "3/icones/misterios_portugues.png", link: "3/pt/misterios-portugues/", ano: "3º Ano" },
	{ nome: "Nomes Comuns Coletivos", icone: "3/icones/comuns_coletivos.png", link: "3/pt/comuns-coletivos/", ano: "3º Ano" },
	{ nome: "Escrita Rápida", icone: "3/icones/escrita_rapida.png", link: "3/pt/escrita-rapida/", ano: "3º Ano" },
	{ nome: "Sopa de Letras", icone: "3/icones/sopa_letras.png", link: "3/pt/sopa-letras/", ano: "3º Ano" },

	// Matemática (mat)
	{ nome: "Tabuadas Turbo", icone: "3/icones/tabuadas_turbo.png", link: "3/mat/tabuadas-turbo/", ano: "3º Ano" },
	{ nome: "Desafios do Mar", icone: "3/icones/desafios_mar.png", link: "3/mat/desafios-mar/", ano: "3º Ano" },
	{ nome: "Adição", icone: "3/icones/adicao.png", link: "3/mat/adicao/", ano: "3º Ano" },
	{ nome: "Subtração", icone: "3/icones/subtracao.png", link: "3/mat/subtracao/", ano: "3º Ano" },
	{ nome: "Subtração com Milhares", icone: "3/icones/subtracao_milhares.png", link: "3/mat/subtracao-milhares/", ano: "3º Ano" },
	{ nome: "O Jacaré Comilão", icone: "3/icones/jacare_comilao.png", link: "3/mat/jacare-comilao/", ano: "3º Ano" },
	{ nome: "Laboratório do Equilíbrio", icone: "3/icones/igualdades.png", link: "3/mat/igualdades/", ano: "3º Ano" },
	{ nome: "Detetive das Coordenadas", icone: "3/icones/coordenadas.png", link: "3/mat/coordenadas/", ano: "3º Ano" },
	{ nome: "O Robô do Ábaco", icone: "3/icones/abaco.png", link: "3/mat/abaco/", ano: "3º Ano" },
	{ nome: "O Chefe das Frações", icone: "3/icones/fracoes.png", link: "3/mat/fracoes/", ano: "3º Ano" },
	{ nome: "Fábrica de Cálculos", icone: "3/icones/fabrica_calculo.png", link: "3/mat/fabrica-calculo/", ano: "3º Ano" },
	{ nome: "O Sapo saltador", icone: "3/icones/sapo_saltador.png", link: "3/mat/sapo-saltador/", ano: "3º Ano" },
	{ nome: "Perímetro e Área", icone: "3/icones/perimetro_area.png", link: "3/mat/perimetro-area/", ano: "3º Ano" },
	{ nome: "Numeração Romana", icone: "3/icones/numeracao_romana.png", link: "3/mat/numeracao-romana/", ano: "3º Ano" },
	{ nome: "As Horas", icone: "3/icones/horas.png", link: "3/mat/horas/", ano: "3º Ano" },
	{ nome: "Arredondamentos", icone: "3/icones/arredondamentos.png", link: "3/mat/arredondamentos/", ano: "3º Ano" },
	{ nome: "Grelha das Tabuadas", icone: "3/icones/grelha_tabuadas.png", link: "3/mat/grelha-tabuadas/", ano: "3º Ano" },
	{ nome: "Cálculo Mental", icone: "3/icones/calculo_mental.png", link: "3/mat/calculo-mental/", ano: "3º Ano" },
	{ nome: "Problemas no Caderno", icone: "3/icones/problemas_caderno.png", link: "3/mat/problemas-caderno/", ano: "3º Ano" },

	// Estudo do Meio (em)
	{ nome: "Direitos da Criança", icone: "3/icones/direitos_crianca.png", link: "3/em/direitos-crianca/", ano: "3º Ano" },
	{ nome: "Saúde e Bem-Estar", icone: "3/icones/saude.png", link: "3/em/saude/", ano: "3º Ano" },
	{ nome: "A Máquina do Tempo", icone: "3/icones/maquina_tempo.png", link: "3/em/maquina-tempo/", ano: "3º Ano" },
	{ nome: "Portugal e a Europa", icone: "3/icones/portugal_europa.png", link: "3/em/portugal-europa/", ano: "3º Ano" },
	{ nome: "A Teia da Vida", icone: "3/icones/teia_vida.png", link: "3/em/teia-vida/", ano: "3º Ano" },
	{ nome: "Terra, Lua e Luz", icone: "3/icones/terra_lua_luz.png", link: "3/em/terra-lua-luz/", ano: "3º Ano" },
	{ nome: "Relevo e Rios", icone: "3/icones/relevo.png", link: "3/em/relevo/", ano: "3º Ano" },
	{ nome: "Continentes e Oceanos", icone: "3/icones/continentes_oceanos.png", link: "3/em/continentes-oceanos/", ano: "3º Ano" },  

	// ------------------------------------
	// 4º ANO
	// ------------------------------------

	// Português (pt)
	{ nome: "Fábrica dos Plurais", icone: "4/icones/fabrica_plurais.png", link: "4/pt/fabrica-plurais/", ano: "4º Ano" },
	{ nome: "Fábrica dos Femininos", icone: "4/icones/fabrica_femininos.png", link: "4/pt/fabrica-femininos/", ano: "4º Ano" },
	{ nome: "Graus dos Adjetivos", icone: "4/icones/graus_adjetivos.png", link: "4/pt/graus-adjetivos/", ano: "4º Ano" },
	{ nome: "O Comboio do Passado", icone: "4/icones/comboio_passado.png", link: "4/pt/comboio-passado/", ano: "4º Ano" },
	{ nome: "A Máquina do Tempo", icone: "4/icones/maquina_tempo.png", link: "4/pt/maquina-tempo/", ano: "4º Ano" },
	{ nome: "O Mistério das Perguntas", icone: "4/icones/misterio_perguntas.png", link: "4/pt/misterio-perguntas/", ano: "4º Ano" },
	{ nome: "O Mundo das Preposições", icone: "4/icones/preposicoes.png", link: "4/pt/preposicoes/", ano: "4º Ano" },
	{ nome: "Truques de Escrita", icone: "4/icones/truques_escrita.png", link: "4/pt/truques-escrita/", ano: "4º Ano" },
	{ nome: "Expressões Idiomáticas", icone: "4/icones/expressoes.png", link: "4/pt/expressoes/", ano: "4º Ano" },
	{ nome: "Nomes Comuns Coletivos", icone: "4/icones/coletivos.png", link: "4/pt/coletivos/", ano: "4º Ano" },
	{ nome: "O Comboio dos Pronomes", icone: "4/icones/pronomes.png", link: "4/pt/pronomes/", ano: "4º Ano" },
	{ nome: "A Ponte dos Conectores", icone: "4/icones/conectores.png", link: "4/pt/conectores/", ano: "4º Ano" },
	{ nome: "A Oficina dos Afixos", icone: "4/icones/afixos.png", link: "4/pt/afixos/", ano: "4º Ano" },
	{ nome: "O Mapa dos Advérbios", icone: "4/icones/adverbios.png", link: "4/pt/adverbios/", ano: "4º Ano" },
	{ nome: "O Polícia da Pontuação", icone: "4/icones/pontuacao.png", link: "4/pt/pontuacao/", ano: "4º Ano" },
	{ nome: "A Montanha das Sílabas", icone: "4/icones/silaba_tonica.png", link: "4/pt/silaba-tonica/", ano: "4º Ano" },
	{ nome: "O Detetive dos Textos", icone: "4/icones/detetive_textos.png", link: "4/pt/detetive-textos/", ano: "4º Ano" },
	{ nome: "O Hospital das Palavras", icone: "4/icones/hospital_palavras.png", link: "4/pt/hospital-palavras/", ano: "4º Ano" },

	// Matemática (mat)
	{ nome: "Mestre do Ábaco", icone: "4/icones/mestre_abaco.png", link: "4/mat/mestre-abaco/", ano: "4º Ano" },
	{ nome: "Detetive dos Números", icone: "4/icones/detetive_numeros.png", link: "4/mat/detetive-numeros/", ano: "4º Ano" },
	{ nome: "Mestre das Tabuadas", icone: "4/icones/mestre_tabuadas.png", link: "4/mat/mestre-tabuadas/", ano: "4º Ano" },
	{ nome: "Mestre dos Vizinhos", icone: "4/icones/mestre_vizinhos.png", link: "4/mat/mestre-vizinhos/", ano: "4º Ano" },
	{ nome: "Missão Aterragem", icone: "4/icones/missao_aterragem.png", link: "4/mat/missao-aterragem/", ano: "4º Ano" },
	{ nome: "Multiplicação X1", icone: "4/icones/multiplicacao_1.png", link: "4/mat/multiplicacao-1/", ano: "4º Ano" },
	{ nome: "Multiplicação X2", icone: "4/icones/multiplicacao_2.png", link: "4/mat/multiplicacao-2/", ano: "4º Ano" },
	{ nome: "Divisão", icone: "4/icones/divisao.png", link: "4/mat/divisao/", ano: "4º Ano" },
	{ nome: "Mestre das Ordens", icone: "4/icones/mestre_ordens.png", link: "4/mat/mestre-ordens/", ano: "4º Ano" },
	{ nome: "Explorador de Decimais", icone: "4/icones/explorador_decimais.png", link: "4/mat/explorador-decimais/", ano: "4º Ano" },
	{ nome: "Super Mente Decimal", icone: "4/icones/mente_decimal.png", link: "4/mat/mente-decimal/", ano: "4º Ano" },
	{ nome: "Regresso ao Início", icone: "4/icones/regresso_inicio.png", link: "4/mat/regresso-inicio/", ano: "4º Ano" },
	{ nome: "Problemas no Caderno", icone: "4/icones/problemas_caderno.png", link: "4/mat/problemas-caderno/", ano: "4º Ano" },

	// Estudo do Meio (em)
	{ nome: "Sistemas do Corpo", icone: "4/icones/sistemas.png", link: "4/em/sistemas/", ano: "4º Ano" },
	{ nome: "Quiz dos Sistemas", icone: "4/icones/sistemas_quiz.png", link: "4/em/sistemas-quiz/", ano: "4º Ano" },
	{ nome: "Antes de Portugal", icone: "4/icones/antes_portugal.png", link: "4/em/antes-portugal/", ano: "4º Ano" },
	{ nome: "As Dinastias", icone: "4/icones/dinastias.png", link: "4/em/dinastias/", ano: "4º Ano" },
	{ nome: "Portugal: O Século XX", icone: "4/icones/portugal_seculo_xx.png", link: "4/em/portugal-seculo-xx/", ano: "4º Ano" },
	{ nome: "Reis de Portugal", icone: "4/icones/reis_portugal.png", link: "4/em/reis/", ano: "4º Ano" },
	{ nome: "Datas Históricas", icone: "4/icones/datas.png", link: "4/em/datas/", ano: "4º Ano" },
	{ nome: "Direitos Humanos", icone: "4/icones/direitos_humanos.png", link: "4/em/direitos-humanos/", ano: "4º Ano" },
	{ nome: "União Europeia", icone: "4/icones/uniao_europeia.png", link: "4/em/uniao-europeia/", ano: "4º Ano" },
	{ nome: "Missão: Espaço", icone: "4/icones/missao_espaco.png", link: "4/em/missao-espaco/", ano: "4º Ano" },
	{ nome: "Terra Viva", icone: "4/icones/terra_viva.png", link: "4/em/terra-viva/", ano: "4º Ano" },
	{ nome: "Sopa de Letras", icone: "4/icones/sopa_letras.png", link: "4/em/sopa-letras/", ano: "4º Ano" },
	{ nome: "Sopa de Letras", icone: "4/icones/sopa_letras_tec.png", link: "4/em/sopa-letras-tec/", ano: "4º Ano" } 

];