const baseDadosAnimais =[
    { id: "leoa", nome: "Leoa", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "carnivoro", rep: "viviparo", emoji: "🦁" },
    { id: "vaca", nome: "Vaca", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "herbivoro", rep: "viviparo", emoji: "🐄" },
    { id: "porco", nome: "Porco", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "omnivoro", rep: "viviparo", emoji: "🐖" },
    { id: "aguia", nome: "Águia", rev: "penas", hab: ["ar"], loc: "voo", ali: "carnivoro", rep: "oviparo", emoji: "🦅" },
    { id: "galinha", nome: "Galinha", rev: "penas", hab: ["terra"], loc: "marcha", ali: "omnivoro", rep: "oviparo", emoji: "🐔" },
    { id: "tubarao", nome: "Tubarão", rev: "escamas", hab: ["agua"], loc: "natacao", ali: "carnivoro", rep: "oviparo", emoji: "🦈" },
    { id: "sardinha", nome: "Sardinha", rev: "escamas", hab: ["agua"], loc: "natacao", ali: "omnivoro", rep: "oviparo", emoji: "🐟" },
    { id: "cobra", nome: "Cobra", rev: "escamas", hab:["terra"], loc: "reptacao", ali: "carnivoro", rep: "oviparo", emoji: "🐍" },
    { id: "ra", nome: "Rã", rev: "pele_nua", hab: ["agua", "terra"], loc: "salto", ali: "carnivoro", rep: "oviparo", emoji: "🐸" },
    { id: "minhoca", nome: "Minhoca", rev: "pele_nua", hab: ["terra"], loc: "reptacao", ali: "omnivoro", rep: "oviparo", emoji: "🪱" },
    { id: "caracol", nome: "Caracol", rev: "concha", hab: ["terra"], loc: "reptacao", ali: "herbivoro", rep: "oviparo", emoji: "🐌" },
    { id: "ostra", nome: "Ostra", rev: "concha", hab: ["agua"], loc: "natacao", ali: "omnivoro", rep: "oviparo", emoji: "🦪" },
    { id: "tartaruga", nome: "Tartaruga", rev: "carapaca", hab: ["agua", "terra"], loc: "marcha", ali: "herbivoro", rep: "oviparo", emoji: "🐢" },
    { id: "caranguejo", nome: "Caranguejo", rev: "carapaca", hab: ["agua", "terra"], loc: "marcha", ali: "omnivoro", rep: "oviparo", emoji: "🦀" },
    { id: "urso", nome: "Urso", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "omnivoro", rep: "viviparo", emoji: "🐻" },
    { id: "coelho", nome: "Coelho", rev: "pelo", hab: ["terra"], loc: "salto", ali: "herbivoro", rep: "viviparo", emoji: "🐰" },
    { id: "canguru", nome: "Canguru", rev: "pelo", hab: ["terra"], loc: "salto", ali: "herbivoro", rep: "viviparo", emoji: "🦘" },
    { id: "crocodilo", nome: "Crocodilo", rev: "escamas", hab: ["agua", "terra"], loc: "reptacao", ali: "carnivoro", rep: "oviparo", emoji: "🐊" },
    { id: "golfinho", nome: "Golfinho", rev: "pele_nua", hab: ["agua"], loc: "natacao", ali: "carnivoro", rep: "viviparo", emoji: "🐬" },
    { id: "baleia", nome: "Baleia", rev: "pele_nua", hab: ["agua"], loc: "natacao", ali: "carnivoro", rep: "viviparo", emoji: "🐋" },
    { id: "gato", nome: "Gato", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "carnivoro", rep: "viviparo", emoji: "🐱" },
    { id: "cao", nome: "Cão", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "omnivoro", rep: "viviparo", emoji: "🐶" },
    { id: "cavalo", nome: "Cavalo", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "herbivoro", rep: "viviparo", emoji: "🐴" },
	{ id: "abelha", nome: "Abelha", rev: "quitina", hab: ["ar", "terra"], loc: "voo", ali: "herbivoro", rep: "oviparo", emoji: "🐝", info: "A abelha é um inseto. O revestimento do seu corpo chama-se <b>quitina</b>." },
    { id: "avestruz", nome: "Avestruz", rev: "penas", hab: ["terra"], loc: "marcha", ali: "omnivoro", rep: "oviparo", emoji: "🪶" },
    { id: "aranha", nome: "Aranha", rev: "quitina", hab: ["terra"], loc: "marcha", ali: "carnivoro", rep: "oviparo", emoji: "🕷️", info: "A aranha é um aracnídeo. O revestimento do seu corpo chama-se <b>quitina</b>." },
    { id: "borboleta", nome: "Borboleta", rev: "quitina", hab: ["ar"], loc: "voo", ali: "herbivoro", rep: "oviparo", emoji: "🦋", info: "A borboleta é um inseto. O revestimento do seu corpo chama-se <b>quitina</b>." },
	{ id: "bode", nome: "Bode", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "herbivoro", rep: "viviparo", emoji: "🐐" },
    { id: "burro", nome: "Burro", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "herbivoro", rep: "viviparo", emoji: "🫏" },
    { id: "camelo", nome: "Camelo", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "herbivoro", rep: "viviparo", emoji: "🐪" },
    { id: "camarao", nome: "Camarão", rev: "carapaca", hab: ["agua"], loc: "natacao", ali: "omnivoro", rep: "oviparo", emoji: "🦐" },
    { id: "carneiro", nome: "Carneiro", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "herbivoro", rep: "viviparo", emoji: "🐏" },
    { id: "cegonha", nome: "Cegonha", rev: "penas", hab: ["ar", "terra"], loc: "voo", ali: "carnivoro", rep: "oviparo", emoji: "🦢" },
    { id: "chimpanze", nome: "Chimpanzé", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "omnivoro", rep: "viviparo", emoji: "🐒" },
    { id: "cisne", nome: "Cisne", rev: "penas", hab: ["agua", "ar"], loc: "natacao", ali: "herbivoro", rep: "oviparo", emoji: "🦢" },
    { id: "coruja", nome: "Coruja", rev: "penas", hab: ["ar"], loc: "voo", ali: "carnivoro", rep: "oviparo", emoji: "🦉" },
    { id: "elefante", nome: "Elefante", rev: "pele_nua", hab: ["terra"], loc: "marcha", ali: "herbivoro", rep: "viviparo", emoji: "🐘" },
    { id: "esquilo", nome: "Esquilo", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "herbivoro", rep: "viviparo", emoji: "🐿️" },
    { id: "foca", nome: "Foca", rev: "pelo", hab: ["agua", "terra"], loc: "natacao", ali: "carnivoro", rep: "viviparo", emoji: "🦭" },
    { id: "formiga", nome: "Formiga", rev: "quitina", hab: ["terra"], loc: "marcha", ali: "omnivoro", rep: "oviparo", emoji: "🐜", info: "A formiga é um inseto. O revestimento do seu corpo chama-se <b>quitina</b>." },
    { id: "gafanhoto", nome: "Gafanhoto", rev: "quitina", hab: ["terra"], loc: "salto", ali: "herbivoro", rep: "oviparo", emoji: "🐜", info: "O gafanhoto é um inseto. O revestimento do seu corpo chama-se <b>quitina</b>." },
    { id: "girafa", nome: "Girafa", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "herbivoro", rep: "viviparo", emoji: "🦒" },
	{ id: "grilo", nome: "Grilo", rev: "quitina", hab: ["terra"], loc: "salto", ali: "herbivoro", rep: "oviparo", emoji: "🦗", info: "O grilo é um inseto. O revestimento do seu corpo chama-se <b>quitina</b>." },
	{ id: "hamster", nome: "Hamster", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "herbivoro", rep: "viviparo", emoji: "🐹" },
    { id: "hipopotamo", nome: "Hipopótamo", rev: "pele_nua", hab: ["agua", "terra"], loc: "marcha", ali: "herbivoro", rep: "viviparo", emoji: "🦛" },
    { id: "jacare", nome: "Jacaré", rev: "escamas", hab: ["agua", "terra"], loc: "reptacao", ali: "carnivoro", rep: "oviparo", emoji: "🐊" },
 	{ id: "joaninha", nome: "Joaninha", rev: "quitina", hab: ["ar", "terra"], loc: "voo", ali: "carnivoro", rep: "oviparo", emoji: "🐞", info: "A joaninha é um inseto. O revestimento do seu corpo chama-se <b>quitina</b>." },
    { id: "leopardo", nome: "Leopardo", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "carnivoro", rep: "viviparo", emoji: "🐆" },
    { id: "lobo", nome: "Lobo", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "carnivoro", rep: "viviparo", emoji: "🐺" },
    { id: "macaco", nome: "Macaco", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "omnivoro", rep: "viviparo", emoji: "🐒" },
    { id: "morcego", nome: "Morcego", rev: "pelo", hab: ["ar"], loc: "voo", ali: "omnivoro", rep: "viviparo", emoji: "🦇" },
    { id: "ovelha", nome: "Ovelha", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "herbivoro", rep: "viviparo", emoji: "🐑" },
    { id: "panda", nome: "Panda", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "herbivoro", rep: "viviparo", emoji: "🐼" },
    { id: "papagaio", nome: "Papagaio", rev: "penas", hab: ["ar"], loc: "voo", ali: "herbivoro", rep: "oviparo", emoji: "🦜" },
    { id: "pavao", nome: "Pavão", rev: "penas", hab: ["terra"], loc: "marcha", ali: "omnivoro", rep: "oviparo", emoji: "🦚" },
    { id: "peixe", nome: "Peixe", rev: "escamas", hab: ["agua"], loc: "natacao", ali: "omnivoro", rep: "oviparo", emoji: "🐟" },
    { id: "peru", nome: "Peru", rev: "penas", hab: ["terra"], loc: "marcha", ali: "omnivoro", rep: "oviparo", emoji: "🦃" },
    { id: "polvo", nome: "Polvo", rev: "pele_nua", hab: ["agua"], loc: "natacao", ali: "carnivoro", rep: "oviparo", emoji: "🐙" },
    { id: "pomba", nome: "Pomba", rev: "penas", hab: ["ar"], loc: "voo", ali: "herbivoro", rep: "oviparo", emoji: "🕊️" },
    { id: "raposa", nome: "Raposa", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "carnivoro", rep: "viviparo", emoji: "🦊" },
    { id: "rato", nome: "Rato", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "omnivoro", rep: "viviparo", emoji: "🐀" },
    { id: "rinoceronte", nome: "Rinoceronte", rev: "pele_nua", hab: ["terra"], loc: "marcha", ali: "herbivoro", rep: "viviparo", emoji: "🦏" },
    { id: "serpente", nome: "Serpente", rev: "escamas", hab: ["terra"], loc: "reptacao", ali: "carnivoro", rep: "oviparo", emoji: "🐍" },
    { id: "tigre", nome: "Tigre", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "carnivoro", rep: "viviparo", emoji: "🐅" },
    { id: "touro", nome: "Touro", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "herbivoro", rep: "viviparo", emoji: "🐂" },
    { id: "tucano", nome: "Tucano", rev: "penas", hab: ["ar"], loc: "voo", ali: "herbivoro", rep: "oviparo", emoji: "🦜" },
    { id: "zebra", nome: "Zebra", rev: "pelo", hab: ["terra"], loc: "marcha", ali: "herbivoro", rep: "viviparo", emoji: "🦓" }
];