const palavrasGramatica = [
    // Nomes Próprios
    { palavra: "André", categoria: "Nomes Próprios" },
    { palavra: "Coimbra", categoria: "Nomes Próprios" },
    { palavra: "Miguel", categoria: "Nomes Próprios" },
    { palavra: "Lisboa", categoria: "Nomes Próprios" },
    { palavra: "Portugal", categoria: "Nomes Próprios" },
    { palavra: "Tejo", categoria: "Nomes Próprios" },
    { palavra: "Maria", categoria: "Nomes Próprios" },
    { palavra: "João", categoria: "Nomes Próprios" },
    { palavra: "Porto", categoria: "Nomes Próprios" },
    { palavra: "Brasil", categoria: "Nomes Próprios" },
    { palavra: "Europa", categoria: "Nomes Próprios" },
    { palavra: "Douro", categoria: "Nomes Próprios" },
    { palavra: "Ana", categoria: "Nomes Próprios" },
    { palavra: "Pedro", categoria: "Nomes Próprios" },
    { palavra: "França", categoria: "Nomes Próprios" },
    { palavra: "Paris", categoria: "Nomes Próprios" },
    { palavra: "Marte", categoria: "Nomes Próprios" },
    { palavra: "Júpiter", categoria: "Nomes Próprios" },
    { palavra: "Sara", categoria: "Nomes Próprios" },
    { palavra: "Tiago", categoria: "Nomes Próprios" },
    { palavra: "Espanha", categoria: "Nomes Próprios" },
    { palavra: "Guadiana", categoria: "Nomes Próprios" },
    { palavra: "Atlântico", categoria: "Nomes Próprios" },
    { palavra: "Angola", categoria: "Nomes Próprios" },
    { palavra: "Inês", categoria: "Nomes Próprios" },
    { palavra: "Rui", categoria: "Nomes Próprios" },
    { palavra: "Madeira", categoria: "Nomes Próprios" },
    { palavra: "Funchal", categoria: "Nomes Próprios" },
    { palavra: "Londres", categoria: "Nomes Próprios" },
    { palavra: "Itália", categoria: "Nomes Próprios" },
    { palavra: "Roma", categoria: "Nomes Próprios" },
    { palavra: "Sofia", categoria: "Nomes Próprios" },
    { palavra: "Carlos", categoria: "Nomes Próprios" },
    { palavra: "África", categoria: "Nomes Próprios" },
    { palavra: "Mondego", categoria: "Nomes Próprios" },
    { palavra: "Açores", categoria: "Nomes Próprios" },
    { palavra: "Faro", categoria: "Nomes Próprios" },
    { palavra: "Beatriz", categoria: "Nomes Próprios" },
    { palavra: "Japão", categoria: "Nomes Próprios" },
    { palavra: "Tóquio", categoria: "Nomes Próprios" },

    // Nomes Comuns
    { palavra: "cão", categoria: "Nomes Comuns" },
    { palavra: "mesa", categoria: "Nomes Comuns" },
    { palavra: "escola", categoria: "Nomes Comuns" },
    { palavra: "menino", categoria: "Nomes Comuns" },
    { palavra: "planeta", categoria: "Nomes Comuns" },
    { palavra: "rio", categoria: "Nomes Comuns" },
    { palavra: "gato", categoria: "Nomes Comuns" },
    { palavra: "carro", categoria: "Nomes Comuns" },
    { palavra: "livro", categoria: "Nomes Comuns" },
    { palavra: "cadeira", categoria: "Nomes Comuns" },
    { palavra: "árvore", categoria: "Nomes Comuns" },
    { palavra: "casa", categoria: "Nomes Comuns" },
    { palavra: "janela", categoria: "Nomes Comuns" },
    { palavra: "computador", categoria: "Nomes Comuns" },
    { palavra: "telemóvel", categoria: "Nomes Comuns" },
    { palavra: "cidade", categoria: "Nomes Comuns" },
    { palavra: "país", categoria: "Nomes Comuns" },
    { palavra: "mar", categoria: "Nomes Comuns" },
    { palavra: "montanha", categoria: "Nomes Comuns" },
    { palavra: "flor", categoria: "Nomes Comuns" },
    { palavra: "pássaro", categoria: "Nomes Comuns" },
    { palavra: "amigo", categoria: "Nomes Comuns" },
    { palavra: "relógio", categoria: "Nomes Comuns" },
    { palavra: "sapato", categoria: "Nomes Comuns" },
    { palavra: "porta", categoria: "Nomes Comuns" },
    { palavra: "rua", categoria: "Nomes Comuns" },
    { palavra: "praia", categoria: "Nomes Comuns" },
    { palavra: "nuvem", categoria: "Nomes Comuns" },
    { palavra: "estrela", categoria: "Nomes Comuns" },
    { palavra: "sol", categoria: "Nomes Comuns" },
    { palavra: "lua", categoria: "Nomes Comuns" },
    { palavra: "peixe", categoria: "Nomes Comuns" },
    { palavra: "barco", categoria: "Nomes Comuns" },
    { palavra: "avião", categoria: "Nomes Comuns" },
    { palavra: "mochila", categoria: "Nomes Comuns" },
    { palavra: "caneta", categoria: "Nomes Comuns" },
    { palavra: "copo", categoria: "Nomes Comuns" },
    { palavra: "prato", categoria: "Nomes Comuns" },
    { palavra: "espelho", categoria: "Nomes Comuns" },
    { palavra: "cama", categoria: "Nomes Comuns" },

    // Verbos
    { palavra: "correr", categoria: "Verbos" },
    { palavra: "dormir", categoria: "Verbos" },
    { palavra: "saltar", categoria: "Verbos" },
    { palavra: "comer", categoria: "Verbos" },
    { palavra: "brincar", categoria: "Verbos" },
    { palavra: "chover", categoria: "Verbos" },
    { palavra: "falar", categoria: "Verbos" },
    { palavra: "escrever", categoria: "Verbos" },
    { palavra: "ler", categoria: "Verbos" },
    { palavra: "cantar", categoria: "Verbos" },
    { palavra: "pensar", categoria: "Verbos" },
    { palavra: "rir", categoria: "Verbos" },
    { palavra: "chorar", categoria: "Verbos" },
    { palavra: "amar", categoria: "Verbos" },
    { palavra: "estudar", categoria: "Verbos" },
    { palavra: "trabalhar", categoria: "Verbos" },
    { palavra: "viajar", categoria: "Verbos" },
    { palavra: "ouvir", categoria: "Verbos" },
    { palavra: "ver", categoria: "Verbos" },
    { palavra: "sentir", categoria: "Verbos" },
    { palavra: "comprar", categoria: "Verbos" },
    { palavra: "vender", categoria: "Verbos" },
    { palavra: "ajudar", categoria: "Verbos" },
    { palavra: "pedir", categoria: "Verbos" },
    { palavra: "sonhar", categoria: "Verbos" },
    { palavra: "andar", categoria: "Verbos" },
    { palavra: "nadar", categoria: "Verbos" },
    { palavra: "desenhar", categoria: "Verbos" },
    { palavra: "pintar", categoria: "Verbos" },
    { palavra: "dançar", categoria: "Verbos" },
    { palavra: "sorrir", categoria: "Verbos" },
    { palavra: "abrir", categoria: "Verbos" },
    { palavra: "fechar", categoria: "Verbos" },
    { palavra: "subir", categoria: "Verbos" },
    { palavra: "descer", categoria: "Verbos" },
    { palavra: "ganhar", categoria: "Verbos" },
    { palavra: "perder", categoria: "Verbos" },
    { palavra: "começar", categoria: "Verbos" },
    { palavra: "terminar", categoria: "Verbos" },
    { palavra: "cozinhar", categoria: "Verbos" },

    // Adjetivos
    { palavra: "amarelo", categoria: "Adjetivos" },
    { palavra: "rápido", categoria: "Adjetivos" },
    { palavra: "bonito", categoria: "Adjetivos" },
    { palavra: "inteligente", categoria: "Adjetivos" },
    { palavra: "feliz", categoria: "Adjetivos" },
    { palavra: "grande", categoria: "Adjetivos" },
    { palavra: "pequeno", categoria: "Adjetivos" },
    { palavra: "triste", categoria: "Adjetivos" },
    { palavra: "lento", categoria: "Adjetivos" },
    { palavra: "azul", categoria: "Adjetivos" },
    { palavra: "verde", categoria: "Adjetivos" },
    { palavra: "forte", categoria: "Adjetivos" },
    { palavra: "fraco", categoria: "Adjetivos" },
    { palavra: "quente", categoria: "Adjetivos" },
    { palavra: "frio", categoria: "Adjetivos" },
    { palavra: "novo", categoria: "Adjetivos" },
    { palavra: "velho", categoria: "Adjetivos" },
    { palavra: "rico", categoria: "Adjetivos" },
    { palavra: "pobre", categoria: "Adjetivos" },
    { palavra: "alto", categoria: "Adjetivos" },
    { palavra: "baixo", categoria: "Adjetivos" },
    { palavra: "simpático", categoria: "Adjetivos" },
    { palavra: "cansado", categoria: "Adjetivos" },
    { palavra: "limpo", categoria: "Adjetivos" },
    { palavra: "sujo", categoria: "Adjetivos" },
    { palavra: "vermelho", categoria: "Adjetivos" },
    { palavra: "escuro", categoria: "Adjetivos" },
    { palavra: "claro", categoria: "Adjetivos" },
    { palavra: "doce", categoria: "Adjetivos" },
    { palavra: "salgado", categoria: "Adjetivos" },
    { palavra: "amargo", categoria: "Adjetivos" },
    { palavra: "macio", categoria: "Adjetivos" },
    { palavra: "duro", categoria: "Adjetivos" },
    { palavra: "pesado", categoria: "Adjetivos" },
    { palavra: "leve", categoria: "Adjetivos" },
    { palavra: "corajoso", categoria: "Adjetivos" },
    { palavra: "medroso", categoria: "Adjetivos" },
    { palavra: "engraçado", categoria: "Adjetivos" },
    { palavra: "chato", categoria: "Adjetivos" },
    { palavra: "elegante", categoria: "Adjetivos" }
];
