// ==========================================
// DADOS DO CORPO HUMANO (Verdadeiro ou Falso)
// ==========================================

const todasAsPerguntas =[
    { imagem: "coracao_esforco.png", emoji: "❤️",  q: "O coração bate mais rápido quando corremos ou saltamos.", hint: "Pensa em como ficas ofegante e como sentes o teu peito depois de brincares muito no recreio.", a: true, expl: "Quando fazemos esforço, o corpo precisa de mais oxigénio, então o coração trabalha mais rápido para enviar mais sangue." },
    { imagem: "coracao_comida.png", emoji: "❤️", q: "A principal função do coração é digerir a comida que comemos.", hint: "Lembra-te para onde vai o teu lanche depois de o engolires.", a: false, expl: "O trabalho do coração não é digerir comida, mas sim enviar o sangue para todas as partes do corpo. O estômago é que faz a digestão." },
    { imagem: "coracao.png", emoji: "❤️", q: "O coração espalha (bombeia) o sangue por todo o nosso corpo.", hint: "Imagina uma bomba de água que leva o líquido através de tubos para a casa toda.", a: true, expl: "O coração age exatamente como uma bomba, empurrando o sangue através das nossas veias e artérias." },
    { imagem: "coracao_cabeca.png", emoji: "❤️", q: "O coração está localizado na nossa cabeça, dentro do crânio.", hint: "Põe a tua mão no corpo onde sentes o bater quando estás assustado.", a: false, expl: "Na nossa cabeça está o cérebro. O coração está localizado no nosso peito, ligeiramente virado para o lado esquerdo." },
    { imagem: "coracao.png", emoji: "❤️", q: "O nosso coração funciona como um motor e nunca para de bater enquanto vivemos.", hint: "O que aconteceria a um carro se o seu motor se desligasse durante a viagem?", a: true, expl: "Mesmo quando estamos a dormir profundamente, o coração continua sempre a trabalhar para nos manter vivos." },
    { imagem: "coracao_peito.png", emoji: "❤️", q: "Se encostarmos a mão no peito, podemos sentir o bater do coração.", hint: "Faz a experiência agora mesmo! Coloca a mão bem colada ao teu peito.", a: true, expl: "O movimento do coração a empurrar o sangue cria um batimento que se sente através da pele e das costelas." },
    { imagem: "pulmoes.png", emoji: "🌬️", q: "Os pulmões são os órgãos que usamos para respirar.", hint: "Eles funcionam como dois balões dentro do nosso peito que se enchem e esvaziam.", a: true, expl: "Os pulmões recebem o ar quando respiramos e tiram dele o oxigénio de que o corpo precisa." },
    { imagem: "pulmoes.png", emoji: "🌬️", q: "O corpo humano adulto ou de uma criança tem três pulmões.", hint: "Pensa na simetria do teu peito: há um do lado esquerdo e... quantos mais?", a: false, expl: "O corpo humano tem apenas dois pulmões, um do lado esquerdo e outro do lado direito do peito." },
    { imagem: "pulmoes_inspirar.png", emoji: "🌬️", q: "Quando inspiramos (puxamos o ar), os nossos pulmões enchem-se de ar.", hint: "Faz uma respiração funda e repara no que acontece ao tamanho do teu peito.", a: true, expl: "O peito levanta-se e expande-se porque os pulmões agem como esponjas ou balões a encher de ar." },
    { imagem: "pulmoes.png", emoji: "🌬️", q: "Os pulmões enchem-se de água quando respiramos normalmente.", hint: "Pensa no ambiente em que os seres humanos vivem: será que vivemos debaixo de água como os peixes?", a: false, expl: "Os nossos pulmões enchem-se exclusivamente de ar. Apenas os peixes retiram oxigénio da água com as guelras." },
    { imagem: "pulmoes.png", emoji: "🌬️", q: "Os pulmões ficam protegidos dentro do nosso peito, muito perto do coração.", hint: "Os órgãos mais importantes do peito ficam todos juntos, abraçados pelas costelas.", a: true, expl: "Eles são vizinhos tão próximos que o pulmão esquerdo é um bocadinho mais pequeno só para dar espaço ao coração." },
    { imagem: "pulmoes_expirar.png", emoji: "🌬️", q: "O ar sai dos nossos pulmões quando expiramos (deitamos o ar fora).", hint: "Experimenta soprar para a palma da tua mão para sentires o vento a sair.", a: true, expl: "A expiração é o movimento de esvaziar os pulmões, deitando fora o ar que o corpo já não precisa." },
    { imagem: "digestao1.png", emoji: "🍎", q: "O estômago é o órgão que transforma e amassa os alimentos que comemos.", hint: "Para onde achas que vai a tua sandes depois de a mastigares e engolires?", a: true, expl: "O estômago é como uma máquina misturadora que transforma a comida numa papa mole para o corpo usar a energia." },
    { imagem: "estomago.png", emoji: "🍎", q: "O estômago fica situado no interior do nosso pescoço.", hint: "Quando tens fome, qual é a zona do corpo que te dói ou faz barulhos?", a: false, expl: "No pescoço fica apenas o tubo (esófago) por onde a comida escorrega. O estômago fica localizado na nossa barriga." },
    { imagem: "digestao.png", emoji: "🍎", q: "O processo onde o estômago desfaz a comida chama-se digestão.", hint: "É uma palavra longa que os pais costumam usar depois do almoço quando te dizem para descansares um bocado.", a: true, expl: "A digestão é exatamente a viagem e a transformação da comida dentro da nossa barriga." },
    { imagem: "mastigar.png", emoji: "🍎", q: "A comida que mastigamos na boca vai direta para os pulmões.", hint: "Lembra-te do que pode acontecer se te engasgares enquanto bebes água.", a: false, expl: "A comida vai para o estômago. Se por acidente for para o caminho dos pulmões, nós tossimos e engasgamo-nos." },
    { imagem: "estomago.png", emoji: "🍎", q: "O estômago parece um saco elástico onde a comida se mistura.", hint: "Quando comes muito num dia de festa, como é que a tua barriga se sente?", a: true, expl: "Ele consegue esticar um bocadinho quando comemos muito para guardar e misturar os alimentos com os sucos digestivos." },
    { imagem: "estomago.png", emoji: "🍎", q: "O estômago é o principal órgão responsável por limpar e filtrar o nosso sangue.", hint: "Há um outro órgão com formato de feijão que faz as limpezas. O estômago só lida com a comida.", a: false, expl: "O estômago cuida da alimentação. A função de limpar o sangue pertence aos rins." },
    { imagem: "rins.png", emoji: "💧", q: "Os rins funcionam como filtros que limpam o nosso sangue.", hint: "Eles são como os coadores de chá ou os filtros de água das piscinas do nosso corpo.", a: true, expl: "Os rins retiram a sujidade e as coisas que fazem mal do nosso sangue para o deixar sempre limpinho." },
    { imagem: "rins.png", emoji: "💧", q: "São os rins que produzem a urina (o chichi).", hint: "Pensa para onde vai toda a sujidade e o excesso de água que é filtrada do sangue.", a: true, expl: "Toda a sujidade e água a mais que os rins tiram do sangue transforma-se no chichi para ir para a rua." },
    { imagem: "rim.png", emoji: "💧", q: "Nós temos apenas um rim no nosso corpo inteiro.", hint: "Estes órgãos trabalham quase sempre aos pares, tal como os pulmões.", a: false, expl: "Nós temos dois rins! Eles ficam na zona das costas, um de cada lado." },
    { imagem: "rins.png", emoji: "💧", q: "Os rins têm um formato muito parecido com o de um grão de feijão.", hint: "Lembra-te das fotografias e desenhos dos órgãos nos livros do Estudo do Meio.", a: true, expl: "A forma natural do rim parece exatamente com um feijão, mas claro que é muito maior que a semente." },
    { imagem: "beber_agua.png", emoji: "💧", q: "Beber muita água ajuda os rins a funcionarem melhor.", hint: "Pensa se é mais fácil limpar a sujidade do chão com bastante água ou sem água nenhuma.", a: true, expl: "A água ajuda os rins a 'lavarem' o sangue com mais facilidade e a fabricarem bem a urina." },
    { imagem: "urina.png", emoji: "💧", q: "A urina vai diretamente do estômago para a sanita.", hint: "Lembra-te que o estômago lida com comida e não com a criação do chichi.", a: false, expl: "A urina é criada nos rins, guardada na bexiga e só depois é que vai para a sanita." },
    { imagem: "esqueleto.png", emoji: "🦴", q: "O esqueleto humano é o conjunto de todos os ossos do nosso corpo.", hint: "Lembra-te do nome que damos ao 'boneco' de ossos que se costuma ver no Halloween.", a: true, expl: "Quando juntamos os mais de 200 ossos que existem no corpo humano, damos a isso o nome de esqueleto." },
    { imagem: "ossos.png", emoji: "🦴", q: "Os ossos são muito moles e dobram-se facilmente como borracha.", hint: "Bate levemente com o teu dedo na cabeça, nos cotovelos ou nos joelhos.", a: false, expl: "Os ossos são extremamente fortes, rijos e resistentes para suportarem o peso do corpo e protegerem os órgãos." },
    { imagem: "esqueleto.png", emoji: "🦴", q: "Os ossos ajudam a suportar o corpo para não cairmos ao chão como gelatina.", hint: "Imagina uma tenda sem os paus de metal para a segurar por dentro.", a: true, expl: "A principal missão do esqueleto é ser a estrutura firme que nos mantém direitos e em pé." },
    { imagem: "cranio.png", emoji: "🦴", q: "O crânio é a caixa de osso duro que protege o nosso cérebro.", hint: "O cérebro é muito mole e sensível. Toca com as mãos na tua cabeça para sentires a proteção.", a: true, expl: "O crânio age como um capacete natural de osso, fechado à volta do nosso cérebro para evitar lesões." },
    { imagem: "bebe.png", emoji: "🦴", q: "As crianças recém-nascidas e os bebés pequeninos não têm ossos nenhuns.", hint: "Como é que um bebé consegue agarrar o teu dedo ou dar pequenos pontapés se não tivesse estrutura?", a: false, expl: "Os bebés nascem com esqueleto! Na verdade, até têm mais ossos do que os adultos (alguns deles depois juntam-se à medida que crescem)." },
    { imagem: "costelas.png", emoji: "🦴", q: "As costelas formam uma 'gaiola' de ossos para proteger o coração e pulmões.", hint: "Passa os dedos nos lados do teu peito e da tua barriga quando respiras fundo.", a: true, expl: "As costelas criam a 'caixa torácica', um escudo que abraça os órgãos mais vitais do peito." },
    { imagem: "leite_queijo.png", emoji: "🦴", q: "O cálcio, que é um mineral que existe no leite e no queijo, faz mal aos ossos.", hint: "Lembra-te do que os professores e os pais dizem sobre beber leitinho para crescer.", a: false, expl: "O cálcio é maravilhoso para os ossos! É ele que os deixa bem duros, fortes e saudáveis." },
    { imagem: "dentes.png", emoji: "🦴", q: "Os dentes também são partes muito duras que fazem parte do esqueleto da cara.", hint: "O que usas para trincar uma maçã ou uma cenoura crua sem te magoares?", a: true, expl: "Os dentes são estruturalmente muito parecidos com os ossos, sendo na verdade a substância mais dura do corpo humano." },
    { imagem: "musculos_1.png", emoji: "💪", q: "Os músculos estão espalhados pelo corpo e ajudam-nos a fazer todos os movimentos.", hint: "Como é que consegues abrir e fechar a mão ou dobrar o braço?", a: true, expl: "É graças à contração (ao encolher e esticar) dos músculos que nós conseguimos caminhar, saltar e brincar." },
    { imagem: "musculos_cara.png", emoji: "💪", q: "Nós não temos nenhum músculo na cara.", hint: "Pensa como consegues sorrir, piscar o olho, fazer caretas ou falar.", a: false, expl: "Temos muitos músculos na cara! São eles que nos deixam sorrir, falar e mostrar expressões." },
    { imagem: "musculos.png", emoji: "💪", q: "Os músculos estão colados aos ossos e puxam-nos para fazer o esqueleto mexer-se.", hint: "Para moveres um boneco articulado, puxas as suas pernas através de cordas ou fios.", a: true, expl: "Eles funcionam como elásticos ligados aos ossos; quando o músculo encolhe, o osso é puxado." },
    { imagem: "exercicio.png", emoji: "💪", q: "Fazer ginástica, correr e brincar ao ar livre ajuda a pôr os nossos músculos mais fortes.", hint: "Quem fica mais forte: alguém que joga à bola todos os dias ou alguém que só fica no sofá?", a: true, expl: "O exercício físico exercita as fibras dos músculos, fazendo-os crescer maiores e mais resistentes." },
    { imagem: "coracao.png", emoji: "💪", q: "Sabias que o coração é, na verdade, um músculo muito especial?", hint: "O coração tem de se mexer e 'espremer-se' sozinho o tempo todo para empurrar o sangue.", a: true, expl: "O coração é feito de tecido muscular incansável, que trabalha sem parar sem termos de pensar nisso." },
    { imagem: "musculos.png", emoji: "💪", q: "Nós só usamos os nossos músculos quando estamos a fazer esforços grandes como correr.", hint: "O que estás a usar agora mesmo para segurar o rato do computador, ler e pestanejar?", a: false, expl: "Usamos os músculos até para as ações mais fáceis: respirar, escrever, sorrir e até estar sentado direitinho." },
    { imagem: "dormir.png", emoji: "💪", q: "O nosso corpo precisa de descansar e dormir para os músculos e órgãos recuperarem a energia.", hint: "Como é que ficas no dia a seguir a teres dormido muito mal?", a: true, expl: "Dormir é essencial para que a máquina do nosso corpo possa descansar, crescer saudável e recarregar baterias." },
    { imagem: "alimentacao_variada.png", emoji: "💪", q: "Ter uma alimentação variada não faz qualquer diferença para a saúde dos órgãos.", hint: "Pensa naquilo que as vitaminas da sopa ou da fruta fazem pelo teu corpo.", a: false, expl: "A alimentação é o nosso 'combustível'. Frutas e legumes dão vitaminas vitais ao estômago, coração, rins e músculos." } 
];

// O tradutor automático de Emojis para o nome das tuas futuras imagens na pasta img/
const dicionarioImagens = {
    "️❤️": "coracao",
    "🌬️": "pulmoes",
    "🍎": "estomago", // Usamos o teu ícone de maçã para ligar ao estômago
    "💧": "rins",
    "🦴": "ossos",
    "💪": "musculos"
};